stages:
  - build
  - upload

build-amd64-debian-jessie:
  stage: build
  image: debian:jessie
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/jessie/
    - mv ../*.deb built-packages/jessie/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-debian-stretch:
  stage: build
  image: debian:stretch
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/stretch/
    - mv ../*.deb built-packages/stretch/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-debian-buster:
  stage: build
  image: debian:buster
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/buster/
    - mv ../*.deb built-packages/buster/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-debian-buster:
  stage: build
  image: debian:buster
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/buster/
    - mv ../*.deb built-packages/buster/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-xenial:
  stage: build
  image: ubuntu:xenial
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/xenial/
    - mv ../*.deb built-packages/xenial/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-bionic:
  stage: build
  image: ubuntu:bionic
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/bionic/
    - mv ../*.deb built-packages/bionic/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-cosmic:
  stage: build
  image: ubuntu:cosmic
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/cosmic/
    - mv ../*.deb built-packages/cosmic/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-disco:
  stage: build
  image: ubuntu:disco
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/disco/
    - mv ../*.deb built-packages/disco/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-eoan:
  stage: build
  image: ubuntu:eoan
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/eoan/
    - mv ../*.deb built-packages/eoan/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-fedora-29:
  stage: build
  image: fedora:29
  script:
    - ./gitlab-build-rpm.sh fedora29
    - mkdir -p built-packages/fedora_29/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/fedora_29/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-fedora-30:
  stage: build
  image: fedora:30
  script:
    - ./gitlab-build-rpm.sh fedora30
    - mkdir -p built-packages/fedora_30/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/fedora_30/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-fedora-31:
  stage: build
  image: fedora:31
  script:
    - ./gitlab-build-rpm.sh fedora31
    - mkdir -p built-packages/fedora_31/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/fedora_31/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-centos8:
  stage: build
  image: centos:8
  script:
    - ./gitlab-build-rpm.sh centos8
    - mkdir -p built-packages/centos_8/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/centos_8/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

upload-packages:
  stage: upload
  image: ubuntu:bionic
  script:
    - ./bintray-upload.sh
  only:
    - tags
